cmake_minimum_required(VERSION 3.25)
add_subdirectory(common/kmpmatch)
add_subdirectory(ch341)
add_subdirectory(ch347)
add_subdirectory(cp2112)
add_subdirectory(ftdi2xx)
add_subdirectory(hydrabus)
add_subdirectory(uart)
add_subdirectory(digispark)
add_subdirectory(kspi)
add_subdirectory(ki2c)
add_subdirectory(kvcan)
add_subdirectory(slcan)

add_subdirectory(candlelight)
add_subdirectory(pcan)
add_subdirectory(raweth)
add_subdirectory(tcpip)
add_subdirectory(udp)
add_subdirectory(w5500)
add_subdirectory(enc28j60)
add_subdirectory(lan8720)
add_subdirectory(websocket)

add_subdirectory(dds)
add_subdirectory(dds_typed)
add_subdirectory(grpc)
add_subdirectory(modbus)
add_subdirectory(mqtt)
add_subdirectory(profibus)

add_subdirectory(systec)